# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: landing-page
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: landing-page
#   minReplicas: 2
#   maxReplicas: 20
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: 80
---
apiVersion: apps/v1
kind: Service
apiVersion: v1
metadata:
  name: landing-page
spec:
  selector:
    app: landing-page
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: meziaris/landing-page:buildnumber
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: landing-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
# spec:
#   rules:
#   - host: landing.mezi.space
#     http:
#       paths:
#       #- path: /
#       - backend:
#           serviceName: landing-page
#           servicePort: 80
